import 'package:flutter/material.dart';

class PatientBrowseTip {
  const PatientBrowseTip({
    required this.title,
    required this.text,
    required this.image,
    required this.icon,
  });

  final String title;
  final String text;
  final String image;
  final IconData icon;
}

const List<PatientBrowseTip> kPatientBrowseTips = [
  PatientBrowseTip(
    title: 'تنظيف يومي',
    text: 'نظّف أسنانك صباحاً ومساءً بانتظام لتقليل تراكم البلاك.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'مدة التنظيف',
    text: 'اجعل كل جلسة تنظيف تستمر دقيقتين على الأقل لتغطية كل الأسطح.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'حركة دائرية',
    text: 'استخدم حركات دائرية لطيفة بدل الفرك العنيف الذي يجرح اللثة.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'زاوية 45',
    text: 'أمل الفرشاة بزاوية 45 درجة نحو خط اللثة لإزالة البلاك بفعالية.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'فرشاة ناعمة',
    text: 'اختر فرشاة ناعمة الشعيرات لتجنب تآكل اللثة والمينا.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'تجديد الفرشاة',
    text: 'استبدل الفرشاة كل 3 أشهر أو عند تباعد الشعيرات.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'فرشاة كهربائية',
    text: 'الفرشاة الكهربائية تساعد من يجد صعوبة في التنظيف اليدوي المنتظم.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'كمية المعجون',
    text: 'حبة بازلاء من المعجون كافية للبالغين ولا داعي للإكثار.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'معجون بالفلورايد',
    text: 'اختر معجوناً يحتوي على الفلورايد لتقوية المينا ضد التسوس.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'معجون الحساسية',
    text: 'عند الحساسية استخدم معجوناً مخصصاً واستمر عليه أسابيع.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'الخيط يومياً',
    text: 'مرّر الخيط مرة يومياً لإزالة بقايا الطعام بين الأسنان.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'طريقة الخيط',
    text: 'شكّل الخيط حرف C حول السن وحرّكه بلطف صعوداً وهبوطاً.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'فرشاة بين الأسنان',
    text: 'استخدم فرشاة بين الأسنان للمسافات الواسعة أو بعد التقويم.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'غسول مطهّر',
    text: 'غسول الفم المطهّر يدعم النظافة لكنه لا يغني عن الفرشاة والخيط.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'توقيت الغسول',
    text: 'استخدم الغسول بعد التنظيف لا قبله حتى لا يغسل الفلورايد مبكراً.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'تنظيف اللسان',
    text: 'اكشط اللسان بلطف يومياً لتقليل البكتيريا ورائحة الفم.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'قبل النوم',
    text: 'تنظيف ما قبل النوم أهم لأن اللعاب يقل ليلاً ويزداد خطر التسوس.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'بعد الإفطار',
    text: 'انتظر 20–30 دقيقة بعد الإفطار الحمضي قبل التنظيف لحماية المينا.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'شطف بعد الأكل',
    text: 'اشطف بالماء بعد الوجبة إذا تعذّر التنظيف فوراً.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'زيارة نصف سنوية',
    text: 'راجع العيادة كل 6 أشهر للفحص والكشف المبكر.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'إزالة الجير',
    text: 'تنظيف الجير عند الطبيب يصل لمناطق لا تبلغها الفرشاة المنزلية.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'أشعة تشخيصية',
    text: 'الصور الشعاعية عند الحاجة تكشف تسوساً مخفياً بين الأسنان.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'ألم ليلي',
    text: 'ألم يزداد ليلاً يستدعي مراجعة طبية وقد يشير لالتهاب عصب.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'حساسية البرد',
    text: 'ألم لحظي من البارد قد يدل على انحسار لثة أو تآكل مينا.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'تورم الخد',
    text: 'تورم الوجه مع ألم قد يعني خراجاً ويحتاج تدخلاً سريعاً.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'كسر السن',
    text: 'احفظ القطعة المكسورة في حليب وراجع الطوارئ فوراً إن أمكن.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'سن مخلوع',
    text: 'عند خلع سن دائم ضع السن في الحليب وتوجّه للطبيب فوراً.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'نزيف متكرر',
    text: 'نزيف اللثة المتكرر علامة التهاب ولا يُتجاهل.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'لثة منحسرة',
    text: 'انحسار اللثة يكشف الجذور ويزيد الحساسية ويحتاج تقييماً.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'جيوب لثوية',
    text: 'عمق الجيوب اللثوية يُقاس عند الطبيب ويحدد خطة العلاج.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'رائحة مستمرة',
    text: 'رائحة فم لا تزول بالتنظيف قد ترتبط باللثة أو الجيوب الأنفية.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'جفاف الفم',
    text: 'جفاف الفم يرفع خطر التسوس؛ زد شرب الماء وراجع أدويتك.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'مضغ علكة بلا سكر',
    text: 'علكة بدون سكر بعد الأكل تحفّز اللعاب وتساعد التعادل الحمضي.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'تقليل الحلويات',
    text: 'اجعل الحلويات ضمن وجبة لا كنقرشة متفرقة طوال اليوم.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'المشروبات الغازية',
    text: 'المشروبات الغازية تهاجم المينا بالحمض والسكر معاً.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'عصير الحمضيات',
    text: 'اشرب العصير مع الوجبة لا رشفة مستمرة لتقليل أثر الحمض.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'القهوة والشاي',
    text: 'اشطف بعد القهوة والشاي لتقليل التصبغات السطحية.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'الثلج الصلب',
    text: 'لا تقضم الثلج؛ الضغط المفاجئ يكسر الحشوات والأسنان.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'فتح العبوات',
    text: 'لا تستخدم أسنانك لفتح الأغطية أو قطع الخيوط.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'قضم الأظافر',
    text: 'عض الأظافر يضغط الأسنان ويحرّك المحاذاة مع الوقت.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'صرير الأسنان',
    text: 'صرير الليل يسبب تآكلاً؛ واقي ليلي يحمي الأسطح.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'واقي رياضي',
    text: 'في الرياضات التلامسية ارتدِ واقي أسنان مخصصاً.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'التدخين',
    text: 'التدخين يضعف اللثة ويؤخر الشفاء ويزيد خطر سرطان الفم.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'الشيشة',
    text: 'الشيشة ليست أقل ضرراً على اللثة والأنسجة الفموية.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'الكحول',
    text: 'الإفراط بالكحول يجفّف الفم ويرتبط بمشاكل أنسجة الفم.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'الحمل واللثة',
    text: 'تغيّر الهرمونات بالحمل يزيد التهاب اللثة؛ نظافة أدق مطلوبة.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'رضّع وأسنان',
    text: 'لا تترك الرضيع ينام بزجاجة الحليب لتقليل تسوس الرضاعة.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'أول زيارة طفل',
    text: 'يفضّل أول فحص عند ظهور السن الأول أو حول عمر سنة.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'إشراف الأطفال',
    text: 'أشرف على تنظيف أسنان الطفل حتى يتقن المهارة وحده.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'معجون الأطفال',
    text: 'استخدم كمية حبة أرز من معجون الأطفال حسب العمر الموصى.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'مص الإصبع',
    text: 'مص الإصبع المطوّل قد يؤثر على نمو الفكين والإطباق.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'التقويم والتنظيف',
    text: 'مع الأسلاك نظّف حول الحاصرات بعناية لتجنب بقع بيضاء.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'تقويم شفاف',
    text: 'أزل التقويم الشفاف عند الأكل ونظّفه يومياً حسب الإرشاد.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'مثبت التقويم',
    text: 'ارتدِ المثبت حسب المدة المطلوبة حتى لا يعود الاعوجاج.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'تيجان الأسنان',
    text: 'نظّف حول حافة التاج جيداً لمنع تسوس عند الحدود.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'زراعة الأسنان',
    text: 'بعد الزراعة التزم بتعليمات العناية لنجاح الالتئام.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'أطقم متحركة',
    text: 'انزع الطقم ليلاً ونظّفه بمحلول مناسب لا بمعجون خشن.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'حشوات قديمة',
    text: 'راجع الحشوات المتشققة أو المرتفعة قبل أن يتسرب التسوس.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'تبييض طبي',
    text: 'التبييض تحت إشراف طبيب آمن أكثر من الوصفات القاسية.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'فحم وليمون',
    text: 'خلطات الفحم والليمون تخشّن المينا وقد تزيد الحساسية.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'عدسات تجميلية',
    text: 'عدسات الأسنان تحتاج تقييماً للمينا والإطباق قبل التركيب.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'فيتامين د',
    text: 'نقص فيتامين د قد يرتبط بصحة العظم الداعم للأسنان.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'الكالسيوم',
    text: 'غذاء غني بالكالسيوم يدعم قوة الأسنان والعظام.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'أطعمة مقرمشة',
    text: 'الجزر والتفاح النيّ يساعدان تنظيفاً ميكانيكياً خفيفاً.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'الجبن بعد الوجبة',
    text: 'قطعة جبن صغيرة بعد الأكل قد تساعد تعادل حموضة الفم.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'السكر المخفي',
    text: 'راقب السكر في الصلصات والعصائر الجاهزة لا الحلويات فقط.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'التمور باعتدال',
    text: 'التمور مفيدة غذائياً لكن لصوقها يتطلب شطفاً أو تنظيفاً.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'الرياضة والماء',
    text: 'أثناء التمرين اشرب ماءً بانتظام لتفادي جفاف الفم.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'التنفس الفموي',
    text: 'التنفس المستمر من الفم يجفّف الأنسجة ويزيد التسوس.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'الشخير والفم',
    text: 'الشخير قد يرتبط بجفاف الفم والحلق؛ قيّم السبب طبياً.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'الأدوية الجافّة',
    text: 'بعض أدوية الضغط والحساسية تسبب جفاف فم؛ أخبر طبيب الأسنان.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'مضاد حيوي',
    text: 'لا تتناول مضاداً حيوياً لألم الأسنان دون تشخيص طبي واضح.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'مسكنات فقط',
    text: 'تسكين الألم دون علاج السبب يؤخر المشكلة ويزيد المضاعفات.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'تقرحات هضمية',
    text: 'بعض أمراض الجهاز الهضمي تظهر تقرحات فموية متكررة.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'السكري واللثة',
    text: 'مرضى السكري أكثر عرضة لالتهاب اللثة ويحتاجون ضبطاً أدق.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'هشاشة العظام',
    text: 'بعض علاجات العظام تؤثر على الفك؛ أخبر الطبيب قبل قلع أو زراعة.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'العلاج الكيميائي',
    text: 'قبل العلاج الكيميائي يُفضّل فحص أسنان لتقليل مضاعفات الفم.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'ثقب الشفة',
    text: 'ثقب الشفة أو اللسان يزيد خطر كسر الأسنان والتهاب اللثة.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'أدوات مشتركة',
    text: 'لا تشارك فرشاة الأسنان لتفادي نقل العدوى.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'تخزين الفرشاة',
    text: 'اترك الفرشاة تجف في مكان مفتوح بعيد عن رذاذ المرحاض.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'سفر ونظافة',
    text: 'جهّز فرشاة ومعجون سفر صغير حتى لا تنقطع عن الروتين.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'بعد القيء',
    text: 'اشطف بالماء فقط وانتظر قبل التنظيف حتى لا تُحك المينا بالحمض.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'تبييض منزلي',
    text: 'لا تزد مدة الجلسات المنزلية عن تعليمات المنتج.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'قوالب غير مخصصة',
    text: 'أي قالب ليلي غير مخصص قد يضغط الأسنان بشكل ضار.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'فحص اللسان',
    text: 'لاحظ تغيّر لون أو تقرحات اللسان التي لا تزول خلال أسبوعين.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'بقع بيضاء',
    text: 'بقع بيضاء ثابتة على الأنسجة تستدعي فحصاً لاستبعاد آفات مبكرة.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'تقرحات متكررة',
    text: 'قلاع متكرر جداً قد يحتاج تقييماً غذائياً أو مناعياً.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'برودة مفاجئة',
    text: 'تجنّب الانتقال الحاد من مشروب ساخن لشديد البرودة.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'مضغ جانب واحد',
    text: 'المضغ على جهة واحدة يسبب إجهاداً مفصلياً غير متوازن.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'ألم المفصل',
    text: 'طرقّة أو ألم عند فتح الفم يستدعي تقييم المفصل الفكي.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'وسادة النوم',
    text: 'وضعية نوم تضغط الخد طويلاً قد تزيد ألم المفصل عند البعض.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'إجهاد وصرير',
    text: 'التوتر يزيد صرير الأسنان؛ تقنيات الاسترخاء تساعد.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
  PatientBrowseTip(
    title: 'تصوير منتظم',
    text: 'احتفظ بسجل زياراتك وصورك لمتابعة التغيّرات عبر السنوات.',
    image: 'assets/images/dfgjhkjgfd.png',
    icon: Icons.water_drop_outlined,
  ),
  PatientBrowseTip(
    title: 'خطة علاجية',
    text: 'التزم بترتيب الخطة العلاجية حتى لا تفشل خطوات لاحقة.',
    image: 'assets/images/sfgdgsfsd.png',
    icon: Icons.no_food_outlined,
  ),
  PatientBrowseTip(
    title: 'مواعيد الأطفال',
    text: 'اجعل زيارة الطفل قصيرة وإيجابية لبناء ثقة طويلة الأمد.',
    image: 'assets/images/dgsfdSDA.png',
    icon: Icons.autorenew_rounded,
  ),
  PatientBrowseTip(
    title: 'خوف من العيادة',
    text: 'أخبر الطبيب بخوفك؛ التخدير والشرح التدريجي يخففان القلق.',
    image: 'assets/images/sgdfzsFD.png',
    icon: Icons.spa_outlined,
  ),
  PatientBrowseTip(
    title: 'سؤال الطبيب',
    text: 'اسأل عن بدائل العلاج والتكلفة المتوقعة قبل البدء.',
    image: 'assets/images/IMG_9520 1.png',
    icon: Icons.brush_rounded,
  ),
  PatientBrowseTip(
    title: 'صور قبل وبعد',
    text: 'وثّق حالتك قبل الإجراءات الكبيرة للمتابعة والطمأنينة.',
    image: 'assets/images/IMG_9521 1.png',
    icon: Icons.health_and_safety_outlined,
  ),
  PatientBrowseTip(
    title: 'عناية بعد القلع',
    text: 'بعد القلع تجنّب المضمضة العنيفة والتدخين حسب تعليمات الطبيب.',
    image: 'assets/images/IMG_20260111_172641_363 1.png',
    icon: Icons.visibility_outlined,
  ),
  PatientBrowseTip(
    title: 'الاستمرارية',
    text: 'روتين بسيط ثابت أغلى قيمة من حملات تنظيف متقطعة.',
    image: 'assets/images/IMG_2026011.png',
    icon: Icons.calendar_month_rounded,
  ),
];
